# Include global puppet settings
import "globals.pp"

# Include project-level global puppet settings, if any
import "globals-project.pp"

# Assign Classes, Defines & Parameters using Hiera
hiera_include("classes")

# Realize Defines, if any
import "defines.pp"


#####
#
# DO NOT EDIT THIS FILE
#
# This is managed by the puppet framework at:
#   https://github.com/tylerwalts/framework-puppet
#
# framework-puppet version: 02ce391 on 2013-12-03_1103
#####
